# Stage 1: Build Stage - Build the React application
FROM node:18-alpine as builder
WORKDIR /app
COPY package.json .
# Install dependencies for the frontend
RUN npm install
COPY . .
# Build the static assets
RUN npm run build

# Stage 2: Production Stage - Serve static assets with Nginx
FROM nginx:alpine
# Copy the built assets from the previous stage to the Nginx public directory
COPY --from=builder /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]