/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface PasswordAnalysis {
  isCompliant: boolean
  strengthScore: number
  entropyBits: number
  patternAnalysis: PatternAnalysis
  feedback: Array<string>
  analysisTimeMs: number
}
export interface PatternAnalysis {
  hasUppercase: boolean
  hasLowercase: boolean
  hasNumbers: boolean
  hasSymbols: boolean
  length: number
  repeatedChars: number
  sequentialChars: number
}
export declare function checkPasswordPolicy(password: string): PasswordAnalysis
export declare function hashPassword(password: string): string
export declare function verifyPasswordHash(password: string, hash: string): boolean
export declare function batchHashPasswords(passwords: Array<string>): Record<string, string>
export declare function hashPasswordSha1(password: string): string
